CREATE FUNCTION [dbo].[HashPassword](@Password NVARCHAR(4000))
RETURNS NVARCHAR(64)
AS
BEGIN
    DECLARE @HashThis NVARCHAR(4000)
    DECLARE @Hash VARBINARY(32)


    SET @HashThis = @Password
    SET @Hash = HASHBYTES('SHA2_256', @HashThis)

    RETURN CONVERT(NVARCHAR(64), @Hash, 1)
END